// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-caAV9H/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-caAV9H/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-dlJsaF/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-dlJsaF/Lp14.tsx")
};
